#!/bin/bash
# cpu calc: https://stackoverflow.com/questions/26791240/how-to-get-percentage-of-processor-use-with-bash
i=0
updv=''
diskv=''
while :; do
    read cpu user nice system idle iowait irq softirq steal guest < /proc/stat
    cpu_active_prev=$((user+system+nice+softirq+steal))
    cpu_total_prev=$((user+system+nice+softirq+steal+idle+iowait))
    sleep 1
    read cpu user nice system idle iowait irq softirq steal guest < /proc/stat
    cpu_active_cur=$((user+system+nice+softirq+steal))
    cpu_total_cur=$((user+system+nice+softirq+steal+idle+iowait))
    cpu_util=$((100*(cpu_active_cur-cpu_active_prev)/(cpu_total_cur-cpu_total_prev)))
    cpu_util=`printf %03d $cpu_util`
    mod=$(expr $i % 120)
    if [ $mod -eq 0 ]
    then
        updv=$(~/scripts/modules/updates-mod)
        diskv=$(~/scripts/modules/disk-mod)
    fi

    BAR_INPUT="%{l}%{B#80000000} $updv $(~/scripts/modules/caps-mod)%{B-}%{c}%{B#80000000} $(~/scripts/modules/wifi-mod) - $(~/scripts/modules/sensor-mod) - $diskv - $cpu_util% - $(~/scripts/modules/mem-mod) %{B-}%{r}%{B#80000000} $(~/scripts/modules/dt-mod) %{B-}"
    echo $BAR_INPUT

    ((i++))
done
